sudo: required
addons:
  sauce_connect: true
  firefox: latest
  chrome: stable
language: node_js
node_js:
- 8.9.4
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm test
branches:
  only:
  - master
  - develop